name: booking_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.5
  image_picker: ^0.8.5+3
  dartz: ^0.10.1
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'Josefin'
      fonts:
        - asset: assets/fonts/josefin_sans.ttf
  assets:
    - assets/images/boarding/
    - assets/images/carousel/
    - assets/images/other/
    - assets/images/places/
